package com.catchyapps.whatsdelete.appactivities.activitydirectchat.selectionhelper;




import com.catchyapps.whatsdelete.appactivities.activitydirectchat.countrymodel.CountryModel;

import java.util.ArrayList;
import java.util.List;

public class CountriesDataRepo {
    public static List<CountryModel> hGetCountriesList() {
        List<CountryModel> dataList = new ArrayList<>();
        dataList.add(new CountryModel("Afghanistan", "+93"));
        dataList.add(new CountryModel("Albania", "+355"));
        dataList.add(new CountryModel("Algeria", "+213"));
        dataList.add(new CountryModel("Andorra", "+376"));
        dataList.add(new CountryModel("Angola", "+244"));
        dataList.add(new CountryModel("Antarctica", "+672"));
        dataList.add(new CountryModel("Antigua and Barbuda", "+268"));
        dataList.add(new CountryModel("American Samoa", "+684 "));
        dataList.add(new CountryModel("Anguilla", "+264"));
        dataList.add(new CountryModel("Argentina", "+54"));
        dataList.add(new CountryModel("Armenia", "+374"));
        dataList.add(new CountryModel("Aruba", "+297"));
        dataList.add(new CountryModel("Australia", "+61"));
        dataList.add(new CountryModel("Austria", "+43"));
        dataList.add(new CountryModel("Azerbaijan", "+994"));
        dataList.add(new CountryModel("Bahamas", "+242"));
        dataList.add(new CountryModel("Bahrain", "+973"));
        dataList.add(new CountryModel("Bangladesh", "+880"));
        dataList.add(new CountryModel("Barbados", "+246"));
        dataList.add(new CountryModel("Belarus", "+375"));
        dataList.add(new CountryModel("Belgium", "+32"));
        dataList.add(new CountryModel("Belize", "+501"));
        dataList.add(new CountryModel("Benin", "+229"));
        dataList.add(new CountryModel("Bermuda", "+441"));
        dataList.add(new CountryModel("Bhutan", "+975"));
        dataList.add(new CountryModel("Bolivia", "+591"));
        dataList.add(new CountryModel("Bosnia and Herzegovina", "+387"));
        dataList.add(new CountryModel("Botswana", "+267"));
        dataList.add(new CountryModel("Brazil", "+55"));
        dataList.add(new CountryModel("British Indian Ocean Territory", "+246"));
        dataList.add(new CountryModel("British Virgin Islands", "+284"));
        dataList.add(new CountryModel("Brunei", "+673"));
        dataList.add(new CountryModel("Bulgaria", "+359"));
        dataList.add(new CountryModel("Burkina Faso", "+226"));
        dataList.add(new CountryModel("Burundi", "+257"));
        dataList.add(new CountryModel("Cambodia", "+855"));
        dataList.add(new CountryModel("Cameroon", "+237"));
        dataList.add(new CountryModel("Canada", "+1"));
        dataList.add(new CountryModel("Cape Verde", "+238"));
        dataList.add(new CountryModel("Cayman Islands", "+345"));
        dataList.add(new CountryModel("Central African Republic", "+236"));
        dataList.add(new CountryModel("Chad", "+235"));
        dataList.add(new CountryModel("Chile", "+56"));
        dataList.add(new CountryModel("China", "+86"));
        dataList.add(new CountryModel("Christmas Island", "+61"));
        dataList.add(new CountryModel("Cocos Islands", "+61"));
        dataList.add(new CountryModel("Colombia", "+57"));
        dataList.add(new CountryModel("Comoros", "+269"));
        dataList.add(new CountryModel("Cook Islands", "+682"));
        dataList.add(new CountryModel("Costa Rica", "+506"));
        dataList.add(new CountryModel("Croatia", "+385"));
        dataList.add(new CountryModel("Cuba", "+53"));
        dataList.add(new CountryModel("Curacao", "+599"));
        dataList.add(new CountryModel("Cyprus", "+357"));
        dataList.add(new CountryModel("Czech Republic", "+420"));
        dataList.add(new CountryModel("Democratic Republic of the Congo", "+243"));
        dataList.add(new CountryModel("Denmark", "+45"));
        dataList.add(new CountryModel("Djibouti", "+253"));
        dataList.add(new CountryModel("Dominica", "+767"));
        dataList.add(new CountryModel("Dominican Republic", "+809"));
        dataList.add(new CountryModel("East Timor", "+670"));
        dataList.add(new CountryModel("Ecuador", "+593"));
        dataList.add(new CountryModel("Egypt", "+20"));
        dataList.add(new CountryModel("El Salvador", "+503"));
        dataList.add(new CountryModel("Equatorial Guinea", "+240"));
        dataList.add(new CountryModel("Eritrea", "+291"));
        dataList.add(new CountryModel("Estonia", "+372"));
        dataList.add(new CountryModel("Ethiopia", "+251"));
        dataList.add(new CountryModel("Falkland Islands", "+500"));
        dataList.add(new CountryModel("Faroe Islands", "+298"));
        dataList.add(new CountryModel("Fiji", "+679"));
        dataList.add(new CountryModel("Finland", "+358"));
        dataList.add(new CountryModel("France", "+33"));
        dataList.add(new CountryModel("French Polynesia", "+689"));
        dataList.add(new CountryModel("Gabon", "+241"));
        dataList.add(new CountryModel("Gambia", "+220"));
        dataList.add(new CountryModel("Georgia", "+995"));
        dataList.add(new CountryModel("Germany", "+49"));
        dataList.add(new CountryModel("Ghana", "+233"));
        dataList.add(new CountryModel("Gibraltar", "+350"));
        dataList.add(new CountryModel("Greece", "+30"));
        dataList.add(new CountryModel("Greenland", "+299"));
        dataList.add(new CountryModel("Grenada", "+473"));
        dataList.add(new CountryModel("Guam", "+671"));
        dataList.add(new CountryModel("Guatemala", "+502"));
        dataList.add(new CountryModel("Guernsey", "++44"));
        dataList.add(new CountryModel("Guinea", "+224"));
        dataList.add(new CountryModel("Guinea-Bissau", "+245"));
        dataList.add(new CountryModel("Guyana", "+592"));
        dataList.add(new CountryModel("Haiti", "+509"));
        dataList.add(new CountryModel("Honduras", "+673"));
        dataList.add(new CountryModel("Brunei", "+504"));
        dataList.add(new CountryModel("Hong Kong", "+852"));
        dataList.add(new CountryModel("Hungary", "+36"));
        dataList.add(new CountryModel("Iceland", "+354"));
        dataList.add(new CountryModel("India", "+91"));
        dataList.add(new CountryModel("Indonesia", "+62"));
        dataList.add(new CountryModel("Iran", "+98"));
        dataList.add(new CountryModel("Iraq", "+964"));
        dataList.add(new CountryModel("Ireland", "+353"));
        dataList.add(new CountryModel("Israel", "+972"));
        dataList.add(new CountryModel("Italy", "+39"));
        dataList.add(new CountryModel("Ivory Coast", "+225"));
        dataList.add(new CountryModel("Jamaica", "+876"));
        dataList.add(new CountryModel("Japan", "+81"));
        dataList.add(new CountryModel("Jordan", "+962"));
        dataList.add(new CountryModel("Kazakhstan", "+7"));
        dataList.add(new CountryModel("Kiribati", "+686"));
        dataList.add(new CountryModel("Kosovo", "+383"));
        dataList.add(new CountryModel("Kuwait", "+965"));
        dataList.add(new CountryModel("Kyrgyzstan", "+996"));
        dataList.add(new CountryModel("Laos", "+856"));
        dataList.add(new CountryModel("Latvia", "+371"));
        dataList.add(new CountryModel("Lebanon", "+961"));
        dataList.add(new CountryModel("Lesotho", "+266"));
        dataList.add(new CountryModel("Liberia", "+231"));
        dataList.add(new CountryModel("Libya", "+218"));
        dataList.add(new CountryModel("Liechtenstein", "+423"));
        dataList.add(new CountryModel("Lithuania", "+370"));
        dataList.add(new CountryModel("Luxembourg", "+352"));
        dataList.add(new CountryModel("Macau", "+853"));
        dataList.add(new CountryModel("Macedonia", "+389"));
        dataList.add(new CountryModel("Madagascar", "+261"));
        dataList.add(new CountryModel("Malawi", "+265"));
        dataList.add(new CountryModel("Malaysia", "+60"));
        dataList.add(new CountryModel("Maldives", "+960"));
        dataList.add(new CountryModel("Mali", "+223"));
        dataList.add(new CountryModel("Malta", "+356"));
        dataList.add(new CountryModel("Marshall Islands", "+692"));
        dataList.add(new CountryModel("Mauritania", "+222"));
        dataList.add(new CountryModel("Mauritius", "+230"));
        dataList.add(new CountryModel("Mayotte", "+262"));
        dataList.add(new CountryModel("Mexico", "+52"));
        dataList.add(new CountryModel("Micronesia", "+691"));
        dataList.add(new CountryModel("Moldova", "+373"));
        dataList.add(new CountryModel("Monaco", "+377"));
        dataList.add(new CountryModel("Mongolia", "+976"));
        dataList.add(new CountryModel("Montenegro", "+382"));
        dataList.add(new CountryModel("Morocco", "+212"));
        dataList.add(new CountryModel("Mozambique", "+258"));
        dataList.add(new CountryModel("Myanmar", "+95"));
        dataList.add(new CountryModel("Namibia", "+264"));
        dataList.add(new CountryModel("Nauru", "+674"));
        dataList.add(new CountryModel("Nepal", "+977"));
        dataList.add(new CountryModel("Netherlands", "+31"));
        dataList.add(new CountryModel("Netherlands Antilles", "+599"));
        dataList.add(new CountryModel("New Caledonia", "+687"));
        dataList.add(new CountryModel("New Zealand", "+64"));
        dataList.add(new CountryModel("Nicaragua", "+505"));
        dataList.add(new CountryModel("Niger", "+227"));
        dataList.add(new CountryModel("Nigeria", "+234"));
        dataList.add(new CountryModel("Niue", "+683"));
        dataList.add(new CountryModel("North Korea", "+850"));
        dataList.add(new CountryModel("Norway", "+47"));
        dataList.add(new CountryModel("Oman", "+698"));
        dataList.add(new CountryModel("Pakistan", "+92"));
        dataList.add(new CountryModel("Palau", "+680"));
        dataList.add(new CountryModel("Palestine", "+970"));
        dataList.add(new CountryModel("Panama", "+507"));
        dataList.add(new CountryModel("Papua New Guinea", "+675"));
        dataList.add(new CountryModel("Paraguay", "+595"));
        dataList.add(new CountryModel("Peru", "+51"));
        dataList.add(new CountryModel("Philippines", "+63"));
        dataList.add(new CountryModel("Pitcairn", "+64"));
        dataList.add(new CountryModel("Poland", "+48"));
        dataList.add(new CountryModel("Portugal", "+351"));
        dataList.add(new CountryModel("Qatar", "+974"));
        dataList.add(new CountryModel("Republic of the Congo", "+242"));
        dataList.add(new CountryModel("Reunion", "+262"));
        dataList.add(new CountryModel("Romania", "+40"));
        dataList.add(new CountryModel("Russia", "+7"));
        dataList.add(new CountryModel("Rwanda", "+250"));
        dataList.add(new CountryModel("Saint Barthelemy", "+590"));
        dataList.add(new CountryModel("Saint Helena", "+290"));
        dataList.add(new CountryModel("Saint Lucia", "+758"));
        dataList.add(new CountryModel("Saint Martin", "+590"));
        dataList.add(new CountryModel("Saint Pierre and Miquelon", "+508"));
        dataList.add(new CountryModel("Saint Vincent and the Grenadines", "+784"));
        dataList.add(new CountryModel("Samoa", "+685"));
        dataList.add(new CountryModel("San Marino", "+378"));
        dataList.add(new CountryModel("Sao Tome and Principe", "+239"));
        dataList.add(new CountryModel("Saudi Arabia", "+966"));
        dataList.add(new CountryModel("Senegal", "+221"));
        dataList.add(new CountryModel("Serbia", "+381"));
        dataList.add(new CountryModel("Seychelles", "+248"));
        dataList.add(new CountryModel("Sierra Leone", "+232"));
        dataList.add(new CountryModel("Singapore", "+65"));
        dataList.add(new CountryModel("Slovakia", "+421"));
        dataList.add(new CountryModel("Slovenia", "+386"));
        dataList.add(new CountryModel("Solomon Islands", "+677"));
        dataList.add(new CountryModel("Somalia", "+252"));
        dataList.add(new CountryModel("South Africa", "+27"));
        dataList.add(new CountryModel("South Korea", "+82"));
        dataList.add(new CountryModel("South Sudan", "+211"));
        dataList.add(new CountryModel("Spain", "+34"));
        dataList.add(new CountryModel("Sri Lanka", "+94"));
        dataList.add(new CountryModel("Sudan", "+249"));
        dataList.add(new CountryModel("Suriname", "+597"));
        dataList.add(new CountryModel("Svalbard and Jan Mayen", "+47"));
        dataList.add(new CountryModel("Swaziland", "+268"));
        dataList.add(new CountryModel("Sweden", "+46"));
        dataList.add(new CountryModel("Switzerland", "+41"));
        dataList.add(new CountryModel("Syria", "+963"));
        dataList.add(new CountryModel("Taiwan", "+886"));
        dataList.add(new CountryModel("Tajikistan", "+992"));
        dataList.add(new CountryModel("Tanzania", "+255"));
        dataList.add(new CountryModel("Thailand", "+66"));
        dataList.add(new CountryModel("Togo", "+228"));
        dataList.add(new CountryModel("Tokelau", "+690"));
        dataList.add(new CountryModel("Tonga", "+676"));
        dataList.add(new CountryModel("Trinidad and Tobago", "+868"));
        dataList.add(new CountryModel("Tunisia", "+216"));
        dataList.add(new CountryModel("Turkey", "+90"));
        dataList.add(new CountryModel("Turkmenistan", "+993"));
        dataList.add(new CountryModel("Turks and Caicos Islands", "+649"));
        dataList.add(new CountryModel("Tuvalu", "+688"));
        dataList.add(new CountryModel("U.S. Virgin Islands", "+340"));
        dataList.add(new CountryModel("Uganda", "+256"));
        dataList.add(new CountryModel("Ukraine", "+380"));
        dataList.add(new CountryModel("United Arab Emirates", "+971"));
        dataList.add(new CountryModel("United Kingdom", "+44"));
        dataList.add(new CountryModel("United States", "+1"));
        dataList.add(new CountryModel("Tunisia", "+598"));
        dataList.add(new CountryModel("Uzbekistan", "+998"));
        dataList.add(new CountryModel("Vanuatu", "+678"));
        dataList.add(new CountryModel("Vatican", "+379"));
        dataList.add(new CountryModel("Venezuela", "+58"));
        dataList.add(new CountryModel("Vietnam", "+84"));
        dataList.add(new CountryModel("Wallis and Futuna", "+681"));
        dataList.add(new CountryModel("Western Sahara", "+212"));
        dataList.add(new CountryModel("Yemen", "+967"));
        dataList.add(new CountryModel("Zambia", "+260"));
        dataList.add(new CountryModel("Zimbabwe", "+263"));
        return dataList;
    }
}
